version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: my-mongo-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    container_name: my-redis-db
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:14-alpine
    container_name: my-postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: otus_app
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/postgres:/docker-entrypoint-initdb.d

volumes:
  mongo-data:
  redis-data:
  postgres-data:
